/**
 * ============================================================================
 * UNIVERSAL FRONTEND & SATEK RULE CATALOG
 * ============================================================================
 */

export const RULE_PRIORITY = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  RECOMMEND: 'RECOMMEND',
  LOW: 'LOW',
  INFO: 'INFO',
};

export const RULE_SEVERITY = {
  CRITICAL: 'HIGH',
  MAJOR: 'MEDIUM',
  RECOMMEND: 'RECOMMEND',
  MINOR: 'LOW',
  INFO: 'INFO',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
};

export const RULE_CATEGORY = {
  COLOR_TOKENS: 'Zero Arbitrary Colors (SSOT)',
  BORDER_RADIUS: 'Semantic Border Radius Tokens',
  THEME_SSOT: 'Design Tokens & CSS Variables',
  ROUTER_ARCHITECTURE: 'Thin Route & Router Architecture',
  NAMING_CONVENTION: 'Naming & Dynamic Param Standard',
  CIRCULAR_DEPENDENCY: 'Module & Circular Import Hygiene',
  BARREL_EXPORTS: 'Barrel Exports & Entrypoint Architecture',
  API_INTEGRATION: 'API & State Management Standards',
  RTK_QUERY: 'RTK Query Cache Tags & Mutation Standard',
  FOLDER_COLOCATION: 'Folder Co-location & Hierarchy Hygiene',
  LAYER_BOUNDARIES: 'Layer Boundary & Architectural Hierarchy',
  TYPE_SAFETY: 'TypeScript Strict Typing & Naming',
  REACT_PATTERNS: 'React Component & Hook Patterns',
  HTML_STANDARDS: 'HTML & Accessibility Standards',
  SECURITY: 'Security & Auth Storage Standards',
  CLEAN_CODE: 'Dead Code & Mock Data Hygiene',
  FORM_VALIDATION: 'Form Management & Yup Validation',
};

export const RULES = [
  // ==========================================================================
  // NHÓM 1: ZERO ARBITRARY COLORS & DESIGN TOKENS
  // ==========================================================================
  {
    code: 'RULE-COLOR-001',
    name: 'Arbitrary Hex / Dynamic Color in ClassName',
    category: RULE_CATEGORY.COLOR_TOKENS,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'tailwind',
    scope: 'Toàn bộ UI Component, Page, Common (src/**/*.{tsx,jsx,ts})',
    description: 'Tuyệt đối không sử dụng arbitrary colors dạng [#...], [var(...)], [rgb(...)], hoặc dynamic [${...}] trong className.',
    fix: 'Thay thế bằng Tailwind semantic tokens từ @theme: text-primary, bg-bg-card, border-border-1, text-primary-navy...',
    matchRegex: /\b(text|bg|border|ring|fill|stroke|from|to|via|outline|shadow|decoration|accent|divide|placeholder)-\[(?:#[0-9a-fA-F]{3,8}|rgba?\([^)]+\)|hsla?\([^)]+\)|oklch\([^)]+\)|oklab\([^)]+\)|hwb\([^)]+\)|color\([^)]+\)|var\(--[^)]+\)|\$\{[^}]+\}|color:[^\]]+)\]/g,
    appliesTo: ['Component', 'Page', 'Common'],
  },
  {
    code: 'RULE-COLOR-002',
    name: 'Raw Hex Literal in Inline Style / SVG',
    category: RULE_CATEGORY.COLOR_TOKENS,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'tailwind',
    scope: 'Inline style & SVG elements (src/**/*.{tsx,jsx}) (Loại trừ file *Brand*, *Logo*, *VietQR* & initial form brandColor)',
    description: 'Không viết cứng mã màu hex dạng #123456 trong inline style, style object hoặc thuộc tính SVG.',
    fix: 'Dùng CSS variables hoặc Tailwind theme tokens: currentColor, var(--color-primary)...',
    matchRegex: /(?:['"`]|(?:fill|stroke)=['"]?)#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\b/g,
    appliesTo: ['Component', 'SVG'],
  },
  {
    code: 'RULE-RADIUS-001',
    name: 'Hardcoded Arbitrary Radius',
    category: RULE_CATEGORY.BORDER_RADIUS,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ UI Component, Card, FormField, Tile, Modal (src/**/*.{tsx,jsx}) (Cho phép rounded-full, rounded-pill, rounded-[inherit], rounded-none và // -- CUSTOM_RADIUS)',
    description: 'Không dùng class bo góc Tailwind mặc định hoặc arbitrary (rounded-2xl, rounded-3xl, rounded-xl, rounded-lg, rounded-md, rounded-sm, rounded-[...]). Cho phép rounded-none, rounded-[inherit], rounded-full và rounded-pill. Có thể dùng // -- CUSTOM_RADIUS khi cần bo góc vi mô đặc thù.',
    fix: 'Thay bằng 4 semantic tokens: rounded-card (Container/Card), rounded-field (Input/Button), rounded-tile (StatCard/ItemBox), rounded-pill/rounded-full (Badge/Pill/Dot/Avatar/Spinner/Switch).',
    matchRegex: /(?:^|[\s"'`])(?:[a-zA-Z0-9_-]+:)*rounded(?:-(?:t|b|l|r|tl|tr|bl|br|s|e|ss|se|ee|es))?-(?:2xl|3xl|xl|lg|md|sm|xs|\[(?!(?:inherit)\])[^\]]+\])/g,
    appliesTo: ['Card', 'Container', 'FormField', 'Tile', 'Badge'],
  },
  {
    code: 'RULE-ZINDEX-001',
    name: 'Non-Standard Arbitrary Z-Index Token',
    category: RULE_CATEGORY.THEME_SSOT,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'tailwind',
    scope: 'Toàn bộ UI Component, Modal, Header, Dropdown (src/**/*.{tsx,jsx,css})',
    description: 'Không tự chế arbitrary z-index tự do (z-[9999], z-[99999]). Bắt buộc dùng thang z-index chuẩn SSOT: z-[1000] (dropdown), z-[1050] (sticky header), z-[1060] (modal), z-[10000] (toast/dialog), z-[10050] (calendar/portal trong modal).',
    fix: 'Thay bằng z-index tokens chuẩn: z-[1000] (Dropdown), z-[1050] (Navbar/Header), z-[1060] (Drawer), z-[10000] (Modal/Toast), z-[10050] (Modal Calendar/Portal).',
    matchRegex: /\bz-\[(?!(?:1000|1050|1060|10000|10050)\])[^\]]+\]/g,
    appliesTo: ['Component', 'Modal', 'Header'],
  },
  {
    code: 'RULE-THEME-001',
    name: 'Legacy UI Design Token Constant Object',
    category: RULE_CATEGORY.THEME_SSOT,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'tailwind',
    scope: 'Toàn bộ file nguồn (src/**/*.{ts,tsx,js,jsx})',
    description: 'Cấm tạo hằng số object lưu design tokens lồng nhau (ADMIN_UI_TOKENS, UI_TOKENS, DESIGN_TOKENS). Phải sử dụng CSS @theme và Tailwind semantic tokens.',
    fix: 'Chuyển toàn bộ design tokens vào src/index.css (@theme) hoặc dùng class utility semantic.',
    matchRegex: /\b(?:export\s+)?const\s+(?:ADMIN_UI_TOKENS|UI_TOKENS|DESIGN_TOKENS|THEME_TOKENS|APP_COLORS)\b/g,
    appliesTo: ['Component', 'Store', 'Config'],
  },
  {
    code: 'RULE-UI-001',
    name: 'Forbidden display: contents on Table & Complex Grid Elements',
    category: RULE_CATEGORY.HTML_STANDARDS,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'universal',
    scope: 'Các phần tử Bảng (table, thead, tbody, tr, th, td) và Data Grid (src/**/*.{tsx,jsx,css})',
    description: 'Cấm sử dụng display: contents (hoặc class contents) trực tiếp trên các thẻ Bảng (table, thead, tbody, tr, th, td) hoặc cấu trúc Data Grid phức tạp do phá vỡ cấu trúc bảng HTML chuẩn và accessibility tree.',
    fix: 'Sử dụng React Fragment (<>...</>) hoặc các thẻ bảng chuẩn (tr, td, th) thay vì ép display: contents lên phần tử bảng.',
    matchRegex: null,
    appliesTo: ['Table', 'Grid', 'Component'],
  },

  // ==========================================================================
  // NHÓM 2: ROUTER & ROUTE ARCHITECTURE
  // ==========================================================================
  {
    code: 'RULE-ROUTE-THIN',
    aliases: ['RULE-ROUTE-001', 'RULE-ROUTE-002'],
    name: 'Thin Route Delegation Pattern Violation',
    category: RULE_CATEGORY.ROUTER_ARCHITECTURE,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'router',
    scope: 'Thư mục src/routes/**/*.{tsx,jsx} (Route files, trừ __root và _layout/pathless)',
    description: 'File trong routes/ phải là Thin Route (< 25 dòng), không chứa JSX giao diện phức tạp và không được trực tiếp gọi state/mutation hooks (useState, useEffect, useQuery, useMutation).',
    fix: 'Chuyển toàn bộ logic state, hooks và JSX sang src/components/{module}/pages/{Module}Page.tsx và render 1 dòng tại route file.',
    matchRegex: null,
    appliesTo: ['Route'],
  },
  {
    code: 'RULE-ROUTE-003',
    name: 'Missing createFileRoute / createLazyFileRoute',
    category: RULE_CATEGORY.ROUTER_ARCHITECTURE,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'router',
    scope: 'Thư mục src/routes/**/*.{tsx,jsx} (Route files, trừ __root và _layout/pathless)',
    description: 'Mọi file trong routes/ (trừ layout/root) bắt buộc phải sử dụng createFileRoute hoặc createLazyFileRoute của TanStack Router.',
    fix: 'Khởi tạo route bằng createFileRoute(\'...\') hoặc createLazyFileRoute(\'...\').',
    matchRegex: null,
    appliesTo: ['Route'],
  },
  {
    code: 'RULE-ROUTE-006',
    name: 'Dead Route File (Missing Route Export)',
    category: RULE_CATEGORY.ROUTER_ARCHITECTURE,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'router',
    scope: 'Thư mục src/routes/**/*.{tsx,jsx} (Tất cả file route)',
    description: 'File route trong routes/ phải export hằng số Route (export const Route = ...).',
    fix: 'Thêm export const Route = createFileRoute(...) hoặc createLazyFileRoute(...).',
    matchRegex: null,
    appliesTo: ['Route'],
  },
  {
    code: 'RULE-PARAM-001',
    name: 'Fragmented Dynamic Param Name',
    category: RULE_CATEGORY.NAMING_CONVENTION,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Tên file dynamic routes trong src/routes/**/$*.tsx',
    description: 'Tên file dynamic route không được dùng tên phân mảnh như $domainId, $ticketId, $aiId, $emailId. Phải dùng $id.tsx hoặc $id.lazy.tsx.',
    fix: 'Đổi tên file thành $id.tsx hoặc $id.lazy.tsx theo chuẩn thống nhất.',
    matchRegex: /\$(?!id\b)[a-zA-Z0-9_]+\.(tsx|ts)/g,
    appliesTo: ['RoutePath'],
  },

  // ==========================================================================
  // NHÓM 3: MODULE & BARREL EXPORTS
  // ==========================================================================
  {
    code: 'RULE-BARREL-001',
    name: 'Missing Feature Barrel Entrypoint',
    category: RULE_CATEGORY.BARREL_EXPORTS,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'architecture',
    scope: 'Thư mục module feature tại src/components/<feature>/index.ts',
    description: 'Mỗi module feature tại src/components/<feature>/ bắt buộc phải có index.ts làm entrypoint duy nhất và export các thư mục con tồn tại (pages, shared, tabs, steps).',
    fix: 'Tạo file src/components/{feature}/index.ts và export * from các thư mục con.',
    matchRegex: null,
    appliesTo: ['FeatureModule'],
  },
  {
    code: 'RULE-BARREL-002',
    name: 'Route Deep Import Violation',
    category: RULE_CATEGORY.BARREL_EXPORTS,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'architecture',
    scope: 'Thư mục src/routes/**/*.{tsx,jsx} khi import component',
    description: 'File trong routes/ bắt buộc phải import Page component thông qua barrel export @/components/<feature>, cấm import sâu từ @/components/<feature>/pages/...',
    fix: 'Sử dụng import { ... } from \'@/components/{feature}\' thay vì import sâu vào pages/.',
    matchRegex: /from\s+['"]@\/components\/[a-zA-Z0-9_-]+\/(?:pages|shared|tabs|steps)\b/g,
    appliesTo: ['Route'],
  },
  {
    code: 'RULE-IMPORT-001',
    name: 'Self Circular Barrel Import',
    category: RULE_CATEGORY.CIRCULAR_DEPENDENCY,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'ci',
    scope: 'Toàn bộ file nguồn src/**/*.{ts,tsx,js,jsx} (Cấm import từ ./index, ./ hoặc . trong cùng thư mục)',
    description: 'Các file trong cùng thư mục không được import từ chính ./index, ./ hoặc . gây vòng lặp import.',
    fix: 'Sử dụng relative import trực tiếp từ file anh em: ./SiblingComponent thay vì ./index hoặc .',
    matchRegex: /from\s+['"](?:\.\/index|\.\/|\.)['"]/g,
    appliesTo: ['Component', 'Utils', 'Helpers'],
  },
  {
    code: 'RULE-IMPORT-003',
    name: 'Upward Layer Architectural Import Violation',
    category: RULE_CATEGORY.LAYER_BOUNDARIES,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'architecture',
    scope: 'Tầng kiến trúc dưới: src/store/**, src/types/**, src/utils/**, src/components/common/**',
    description: 'Cấm import ngược tầng kiến trúc: store/types/utils không được import từ components/routes; components/common không được import từ components/<feature>.',
    fix: 'Chuyển dependency theo chiều xuôi: components phụ thuộc store/types/utils, không được import ngược.',
    matchRegex: null,
    appliesTo: ['Store', 'Types', 'Utils', 'Common'],
  },
  {
    code: 'RULE-API-002',
    name: 'Deep API Slice Import Violation',
    category: RULE_CATEGORY.CIRCULAR_DEPENDENCY,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ Component & Pages (src/components/**/*.{tsx,jsx}, src/routes/**/*.{tsx,jsx})',
    description: 'Component không được import sâu từ @/store/api/*Api. Phải import qua barrel tập trung @/store/api.',
    fix: 'Import toàn bộ API hooks thông qua barrel export tập trung: import { ... } from \'@/store/api\'.',
    matchRegex: /from\s+['"]@\/store\/api\/[a-zA-Z0-9]+Api['"]/g,
    appliesTo: ['Component', 'Pages'],
  },

  // ==========================================================================
  // NHÓM 4: API & RTK QUERY STANDARDS
  // ==========================================================================
  {
    code: 'RULE-API-001',
    name: 'Direct Raw Fetch / Axios Outside BaseApi',
    category: RULE_CATEGORY.API_INTEGRATION,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'universal',
    scope: 'Toàn bộ file nguồn ngoài src/store/api/baseApi.ts',
    description: 'Không được gọi raw fetch(), axios, hoặc createApi() trực tiếp ngoài baseApi.ts.',
    fix: 'Sử dụng baseApi.injectEndpoints() để tự động kế thừa cơ chế 401 refresh mutex.',
    matchRegex: /(?:\b(?:window\.|globalThis\.)?fetch\s*\(|\baxios(?:\.[a-zA-Z0-9_$]+)?\s*\(|\bcreateApi\s*\()/g,
    appliesTo: ['Store', 'Component'],
  },
  {
    code: 'RULE-RTK-001',
    name: 'Missing invalidatesTags in RTK Query Resource Mutation',
    category: RULE_CATEGORY.RTK_QUERY,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'architecture',
    scope: 'Các Mutation quản lý CRUD Resource (Ngoại trừ: authApi, uploadApi/fileApi, lookup/check tools, và mutation có onQueryStarted)',
    description: 'Các mutation thay đổi dữ liệu tài nguyên (Create, Update, Delete) trong src/store/api/*.ts bắt buộc phải cấu hình invalidatesTags để tự động làm mới cache. Không áp dụng cho các API stateless như Auth, Upload, Check/Lookup hoặc mutation đã tự cập nhật qua onQueryStarted.',
    fix: 'Thêm invalidatesTags: [\'TagName\'] vào cấu hình builder.mutation({ ... }) (hoặc chú thích // -- LOGIC: nếu là mutation đặc thù).',
    matchRegex: null,
    appliesTo: ['ApiSlice'],
  },
  {
    code: 'RULE-RTK-002',
    name: 'Missing providesTags in RTK Query Resource Query',
    category: RULE_CATEGORY.RTK_QUERY,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'architecture',
    scope: 'Các Query lấy dữ liệu Resource danh sách & chi tiết (Ngoại trừ: authApi, check/lookup on-the-fly, healthcheck)',
    description: 'Các query lấy dữ liệu tài nguyên trong src/store/api/*.ts bắt buộc phải cấu hình providesTags để liên kết cache với các mutation tương ứng.',
    fix: 'Thêm providesTags: [\'TagName\'] vào cấu hình builder.query({ ... }).',
    matchRegex: null,
    appliesTo: ['ApiSlice'],
  },
  {
    code: 'RULE-RTK-TAG-NAMING',
    name: 'Non-Standard RTK Query Cache Tag Name',
    category: RULE_CATEGORY.RTK_QUERY,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'architecture',
    scope: 'Các file API Slice trong src/store/api/*.ts',
    description: 'Tên Tag trong providesTags và invalidatesTags bắt buộc phải theo chuẩn PascalCase và thuộc danh sách Resource Tags chuẩn của dự án.',
    fix: 'Đặt tên Tag theo chuẩn PascalCase: Domain, Customer, Order, Product, Mailserver, Transaction, User, AiService, Hosting, Employee...',
    matchRegex: null,
    appliesTo: ['ApiSlice'],
  },

  // ==========================================================================
  // NHÓM 5: FOLDER CO-LOCATION & HIERARCHY HYGIENE
  // ==========================================================================
  {
    code: 'RULE-FOLDER-002',
    name: 'Misplaced Single-use Component in shared/',
    category: RULE_CATEGORY.FOLDER_COLOCATION,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'architecture',
    scope: 'Thư mục src/components/<feature>/shared/*.tsx',
    description: 'Thư mục components/<feature>/shared/ chỉ chứa component được gọi từ 2 trang/tab/step trở lên hoặc các component layout đặc thù (*Header, *Tabs, *Table, *Layout, *Wrapper, *Summary).',
    fix: 'Chuyển component dùng 1 lần về đúng thư mục Tab/Step sử dụng nó, hoặc đổi tên theo chuẩn shared component.',
    matchRegex: null,
    appliesTo: ['SharedComponent'],
  },
  {
    code: 'RULE-FOLDER-003',
    name: 'Legacy or Dead Feature Folder Detected',
    category: RULE_CATEGORY.FOLDER_COLOCATION,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'architecture',
    scope: 'Thư mục cấu trúc phẳng cũ tại src/components/<feature>/{components,forms}/',
    description: 'Cấm tồn tại các thư mục phẳng legacy cũ (components/<feature>/components, forms) sau khi feature đã cấu trúc lại theo pages/, shared/, tabs/, steps/ (Ngoại trừ module auth gom forms hoặc thư mục có export trong index.ts).',
    fix: 'Di chuyển toàn bộ component sang tabs/, steps/ hoặc pages/ và xóa bỏ thư mục phẳng cũ.',
    matchRegex: null,
    appliesTo: ['DirectoryStructure'],
  },

  // ==========================================================================
  // NHÓM 6: TYPESCRIPT STRICT TYPING & NAMING
  // ==========================================================================
  {
    code: 'RULE-TYPE-001',
    name: 'Explicit Any / Unsafe Type Casting',
    category: RULE_CATEGORY.TYPE_SAFETY,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ file TypeScript (src/**/*.{ts,tsx})',
    description: 'Cấm sử dụng kiểu any, Record<string, any> hoặc (x as any).',
    fix: 'Sử dụng unknown kèm type narrowing, hoặc mở rộng interface tại src/types/.',
    matchRegex: /:\s*any\b|\bas\s+any\b|Record<string,\s*any>/g,
    appliesTo: ['TypeScript'],
  },
  {
    code: 'RULE-TYPE-002',
    name: 'Types Must Be Imported From @/types Barrel',
    category: RULE_CATEGORY.TYPE_SAFETY,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ file ngoài src/types/ (Bắt buộc import từ @/types barrel)',
    description: 'Type và Interface bắt buộc phải được import thông qua barrel @/types, cấm deep import từ @/types/*.types.',
    fix: 'Thay đổi import thành: import { ... } from \'@/types\'.',
    matchRegex: /from\s+['"]@\/types\/[a-zA-Z0-9_-]+(?:\.types)?['"]/g,
    appliesTo: ['TypeScript'],
  },
  {
    code: 'RULE-TYPE-003',
    name: 'Invalid Type File Naming in src/types/',
    category: RULE_CATEGORY.TYPE_SAFETY,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Thư mục src/types/*.ts (Trừ index.ts và index.d.ts)',
    description: 'File trong src/types/ (trừ index.ts) bắt buộc phải có đuôi .types.ts hoặc .dto.ts và bắt đầu bằng chữ thường (vd: auth.types.ts, domain.dto.ts).',
    fix: 'Đổi tên file thành {module}.types.ts hoặc {module}.dto.ts và dùng chữ cái thường đầu dòng.',
    matchRegex: null,
    appliesTo: ['TypesDirectory'],
  },

  // ==========================================================================
  // NHÓM 7: REACT, HTML & RADIX STANDARDS
  // ==========================================================================
  {
    code: 'RULE-RADIX-001',
    name: 'Radix Trigger Wrapping Interactive Element Must Use asChild',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'universal',
    scope: 'Toàn bộ Radix UI Triggers (DialogTrigger, PopoverTrigger, TooltipTrigger, DropdownMenuTrigger...)',
    description: 'Radix Trigger (DialogTrigger, PopoverTrigger, TooltipTrigger, DropdownMenuTrigger) khi bọc button hoặc thẻ tương tác bắt buộc phải có thuộc tính asChild.',
    fix: 'Thêm thuộc tính asChild vào thẻ Trigger: <PopoverTrigger asChild><button>...</button></PopoverTrigger>.',
    matchRegex: null,
    appliesTo: ['Component'],
  },
  {
    code: 'RULE-HTML-NESTING',
    aliases: ['RULE-HTML-001', 'RULE-HTML-002'],
    name: 'Invalid HTML Element Nesting in JSX',
    category: RULE_CATEGORY.HTML_STANDARDS,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'universal',
    scope: 'Toàn bộ JSX elements (src/**/*.{tsx,jsx}) (Lồng button/a hoặc lồng th/td)',
    description: 'Cấm lồng các phần tử tương tác vào nhau trong JSX (<button><button>, <a><button>) hoặc lồng các ô bảng vào nhau (<th><th>, <td><td>).',
    fix: 'Tách biệt các thẻ tương tác và đặt các thẻ <th>, <td> cùng cấp bên trong <tr>.',
    matchRegex: null,
    appliesTo: ['JSX'],
  },
  {
    code: 'RULE-EFFECT-GUARD',
    name: 'Missing State Guard in useEffect Hook',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'react',
    scope: 'Toàn bộ React useEffect hooks (src/**/*.{tsx,jsx,ts})',
    description: 'Lệnh setState bên trong useEffect bắt buộc phải có guard điều kiện (if (data && data !== localState)) để chống re-render loop.',
    fix: 'Bọc lệnh setState trong khối kiểm tra điều kiện: if (data && data !== localState) { setState(data); }.',
    matchRegex: null,
    appliesTo: ['Component'],
  },
  {
    code: 'RULE-COMPONENT-001',
    name: 'Nested Component Definition in Parent Function',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ React Component functions (src/**/*.{tsx,jsx})',
    description: 'Cấm định nghĩa component con bên trong hàm render của component cha (Static Component Extraction).',
    fix: 'Đưa định nghĩa component con ra ngoài phạm vi hàm của component cha để tránh render recreate.',
    matchRegex: null,
    appliesTo: ['Component'],
  },
  {
    code: 'RULE-STATE-001',
    name: 'Non-Standard Boolean UI State Naming',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ React useState hooks trong src/**/*.{tsx,jsx}',
    description: 'State boolean UI đóng/mở/hiển thị phải có tiền tố is[Feature][State] (ví dụ: isModalOpen, isFilterVisible).',
    fix: 'Đổi tên state thành is[Feature][State], ví dụ: isPasswordVisible thay vì showPassword, isModalOpen thay vì openModal.',
    matchRegex: /const\s+\[(show[A-Z][A-Za-z0-9_]*|open[A-Z][A-Za-z0-9_]*|visible[A-Z][A-Za-z0-9_]*),\s*set[A-Z][A-Za-z0-9_]*\]\s*=\s*useState/g,
    appliesTo: ['Component'],
  },
  {
    code: 'RULE-REACT-001',
    name: 'Avoid Namespace React.FC / React.ReactNode',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ file TypeScript React (src/**/*.{ts,tsx})',
    description: 'Không dùng namespace React.FC, React.ReactNode, React.MouseEvent. Import từng phần: import type { FC, ReactNode } from "react".',
    fix: 'Import trực tiếp type từ react: import type { FC, ReactNode } from \'react\'.',
    matchRegex: /\bReact\.(?:FC|ReactNode|ComponentProps|MouseEvent|ChangeEvent|FormEvent|KeyboardEvent|CSSProperties|PropsWithChildren)\b/g,
    appliesTo: ['TypeScript'],
  },

  // ==========================================================================
  // NHÓM 8: CLEAN CODE, SECURITY & MOCKS
  // ==========================================================================
  {
    code: 'RULE-STORAGE-001',
    name: 'Raw String Keys in Auth Storage',
    category: RULE_CATEGORY.SECURITY,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'ci',
    scope: 'Toàn bộ file trong src/ có gọi localStorage (Auth & Token)',
    description: 'Cấm truyền string literal tùy tiện vào localStorage cho token và auth (localStorage.getItem("access_token")). Bắt buộc dùng hằng số AUTH_STORAGE_KEYS.',
    fix: 'Sử dụng hằng số chuẩn: localStorage.getItem(AUTH_STORAGE_KEYS.ACCESS_TOKEN).',
    matchRegex: /localStorage\.(?:getItem|setItem|removeItem)\(['"](?:access_token|refresh_token|token|authToken|user_token)['"]/g,
    appliesTo: ['Store', 'Component', 'Auth'],
  },
  {
    code: 'RULE-CLEAN-EXPRESSION',
    aliases: ['RULE-MOCK-001', 'RULE-DEAD-001'],
    name: 'Dead Expression or Fake Metric Fallback in JSX',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ JSX Component & Metric displays (src/**/*.{tsx,jsx})',
    description: 'Tuyệt đối không sử dụng biểu thức {false && <Component />} hoặc fallback số liệu giả như || 7, ?? 4010 trong JSX hiển thị.',
    fix: 'Sử dụng khối comment JSX {/* ... */} hoặc biến cờ điều kiện động; dùng giá trị mặc định thực tế 0.',
    matchRegex: /(?:\{\s*false\s*&&|\|\|\s*\d{2,}\b|\?\?\s*\d{2,}\b|\|\|\s*7\b|\?\?\s*7\b)/g,
    appliesTo: ['JSX', 'Component', 'Mocks'],
  },
  {
    code: 'RULE-MOCK-002',
    name: 'Production Code Importing From Mock Modules',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'ci',
    scope: 'Mã nguồn production (src/components/**, src/routes/**, src/store/**)',
    description: 'Cấm import mock data (@/mocks/*, ../mocks/*) trong các file nguồn production (components/, pages/, routes/).',
    fix: 'Thay thế dữ liệu mock bằng RTK Query hooks hoặc API service thực tế.',
    matchRegex: null,
    appliesTo: ['Component', 'Routes'],
  },
  {
    code: 'RULE-CONSOLE-001',
    name: 'Production console.log Statement',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Mã nguồn production (src/**/*.{ts,tsx,js,jsx}) ngoài src/utils/logger và test files',
    description: 'Cấm sử dụng console.log, console.debug, console.info trong mã nguồn production. Sử dụng logger utility nếu cần ghi log.',
    fix: 'Xóa bỏ console statement hoặc dùng logger module chuyên dụng.',
    matchRegex: /\bconsole\.(?:log|debug|info)\s*\(/g,
    appliesTo: ['Component', 'Store', 'Routes'],
  },
  {
    code: 'RULE-SUPPRESS-001',
    name: 'Suppression Comments Without Justification',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ file nguồn có comment vô hiệu hóa linter (@ts-ignore, @ts-expect-error, eslint-disable)',
    description: 'Comment vô hiệu hóa linter (@ts-ignore, @ts-expect-error, eslint-disable) bắt buộc phải có phần giải thích lý do sau dấu -- LOGIC: ...',
    fix: 'Thêm lý do giải thích rõ ràng sau comment: // eslint-disable-next-line -- LOGIC: lý do tại đây.',
    matchRegex: /(?:\/\/|\/\*)\s*(?:@ts-ignore|@ts-nocheck|@ts-expect-error|eslint-disable(?:-next-line)?(?:\s+[\w\-,\s\/]+)?)\s*(?!--\s*LOGIC:)(?:\*\/)?$/g,
    appliesTo: ['Component', 'Store', 'TypeScript'],
  },
  {
    code: 'RULE-I18N-001',
    name: 'Hardcoded Vietnamese UI Text in JSX',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Các component có sử dụng i18n (import useTranslation) hoặc routes/auth/cart (src/**/*.{tsx,jsx,ts})',
    description: 'Không viết cứng chuỗi tiếng Việt có dấu thanh trực tiếp trong JSX của các component đa ngôn ngữ. Phải sử dụng hàm dịch trans(\'...\').',
    fix: 'Bọc chuỗi hiển thị bằng trans(\'...\') hoặc khai báo trong src/locales/.',
    matchRegex: null,
    appliesTo: ['JSX'],
  },
  {
    code: 'RULE-I18N-002',
    name: 'Unused Locale Translation Key in src/locales/',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'clean',
    scope: 'Thư mục src/locales/**/*.{ts,json}',
    description: 'Phát hiện translation keys trong file locales không được bất kỳ file nào trong src/ sử dụng (dead translation keys). Không dùng thì không nên dịch.',
    fix: 'Xóa bỏ translation key không sử dụng trong file locales để giảm dung lượng bundle.',
    matchRegex: null,
    appliesTo: ['Locales'],
  },
  {
    code: 'RULE-ROUTE-005',
    name: 'Prefer <Link> for Static Navigation',
    category: RULE_CATEGORY.ROUTER_ARCHITECTURE,
    severity: RULE_SEVERITY.INFO,
    preset: 'migration',
    scope: 'Toàn bộ static onClick navigation (src/**/*.{tsx,jsx})',
    description: 'Khuyến nghị sử dụng component <Link to="..."> thay vì gọi router.navigate() hoặc navigate({ to: \'...\' }) trong onClick tĩnh.',
    fix: 'Thay thế button onClick={navigate} bằng <Link to="...">...</Link>.',
    matchRegex: null,
    appliesTo: ['Component', 'Pages'],
  },
  {
    code: 'RULE-CUSTOM-001',
    name: 'Excessive Arbitrary Tailwind Classes',
    category: RULE_CATEGORY.THEME_SSOT,
    severity: RULE_SEVERITY.INFO,
    preset: 'migration',
    scope: 'Toàn bộ JSX className (src/**/*.{tsx,jsx}) (> 3 arbitrary classes [..])',
    description: 'Phần tử có quá nhiều arbitrary utilities dạng [...] (> 3 arbitrary classes). Nên trích xuất thành class utility hoặc component chuẩn.',
    fix: 'Sử dụng các class Tailwind chuẩn hoặc trích xuất biến thể component dùng chung.',
    matchRegex: null,
    appliesTo: ['Component'],
  },

  // ==========================================================================
  // NHÓM MỚI V3: KIẾN TRÚC, QUERY CONTRACT & REPOSITORY ADVISORY
  // ==========================================================================
  {
    code: 'RULE-IMPORT-004',
    name: 'Disallow Relative Imports Ascending >= 2 Levels (../../)',
    category: RULE_CATEGORY.LAYER_BOUNDARIES,
    severity: RULE_SEVERITY.HIGH,
    scope: 'Toàn bộ mã nguồn (src/**/*.{ts,tsx,js,jsx})',
    description: 'Cấm sử dụng import/export relative đi lên từ 2 cấp trở lên (../../).',
    fix: 'Thay bằng alias path chuẩn (@/components/..., @/store/..., @/types...).',
    appliesTo: ['All'],
  },
  {
    code: 'RULE-BARREL-003',
    name: 'Public Barrels Required for Shared Packages',
    category: RULE_CATEGORY.BARREL_EXPORTS,
    severity: RULE_SEVERITY.HIGH,
    scope: 'src/{hooks,constants,utils,helpers,store/slices}',
    description: 'Bắt buộc phải có public barrel index.ts cho các package dùng chung.',
    fix: 'Tạo index.ts và re-export các thành phần public.',
    appliesTo: ['Shared'],
  },
  {
    code: 'RULE-FOLDER-004',
    name: 'Common Kit 7-Group Architecture',
    category: RULE_CATEGORY.FOLDER_COLOCATION,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'src/components/common/',
    description: 'Thư mục common được chuẩn hóa theo 7 nhóm: cards, feedback, forms, navigation, system, table, ui.',
    fix: 'Phân loại các common component vào đúng 1 trong 7 nhóm.',
    appliesTo: ['Common'],
  },
  {
    code: 'RULE-WORKFLOW-001',
    name: 'Workflow Steps Folder Co-location',
    category: RULE_CATEGORY.FOLDER_COLOCATION,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'src/components/**/{steps,*-steps}/',
    description: 'Component kết thúc bằng Step.tsx phải được đặt trong thư mục steps/ hoặc *-steps/.',
    fix: 'Di chuyển component Step vào thư mục steps/ tương ứng.',
    appliesTo: ['Workflow'],
  },
  {
    code: 'RULE-NAMING-001',
    name: 'Role-based Component & File Naming',
    category: RULE_CATEGORY.NAMING_CONVENTION,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'src/components/**/*.tsx',
    description: 'Component TSX phải theo PascalCase; vai trò Page, Tab, Step phải có hậu tố tương ứng.',
    fix: 'Đổi tên component và file theo đúng vai trò orchestrator.',
    appliesTo: ['Component'],
  },
  {
    code: 'RULE-QUERY-001',
    name: 'Isolate Status & UI-Only Fields Before Request',
    category: RULE_CATEGORY.API_INTEGRATION,
    severity: RULE_SEVERITY.HIGH,
    scope: 'src/store/api/**/*.ts',
    description: 'Cô lập status, search, và các trường UI-only trước khi gửi request API; cấm raw ...params.',
    fix: 'Map params tường minh trong query callback.',
    appliesTo: ['API'],
  },
  {
    code: 'RULE-QUERY-006',
    name: 'Standard SearchFields Operators & Delimiters',
    category: RULE_CATEGORY.API_INTEGRATION,
    severity: RULE_SEVERITY.HIGH,
    scope: 'src/**/*.{ts,tsx}',
    description: 'searchFields phải sử dụng đúng 10 toán tử chuẩn (lk, eq, ne, gt, gte, lt, lte, in, nin, bt) và delimiter ; / :.',
    fix: 'Kiểm tra lại toán tử tìm kiếm trong query args.',
    appliesTo: ['Query'],
  },
  {
    code: 'RULE-RTK-003',
    name: 'RTK Query Cache Tag Integrity & Natural ID',
    category: RULE_CATEGORY.RTK_QUERY,
    severity: RULE_SEVERITY.HIGH,
    scope: 'src/store/api/**/*.ts',
    description: 'Query list phải có LIST tag; mutation phải invalidate LIST tag; cấm String(id) trong tag ID.',
    fix: 'Sử dụng id tự nhiên và cung cấp đầy đủ cache tags.',
    appliesTo: ['API'],
  },
  {
    code: 'RULE-RESPONSE-001',
    name: 'Avoid Trivial 1-1 Unwrap in transformResponse',
    category: RULE_CATEGORY.API_INTEGRATION,
    severity: RULE_SEVERITY.LOW,
    scope: 'src/store/api/**/*.ts',
    description: 'Khuyến nghị bỏ transformResponse unwrap 1-1 đơn thuần; transform phức tạp cần explicit types.',
    fix: 'Xóa bỏ transformResponse nếu chỉ unwrap response?.data.',
    appliesTo: ['API'],
  },
  {
    code: 'RULE-MEMO-001',
    name: 'Avoid Useless useMemo on Query Property Read',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.LOW,
    scope: 'src/**/*.{ts,tsx}',
    description: 'Cấm useMemo chỉ để đọc thuộc tính thuần túy từ query response (response?.data).',
    fix: 'Gán biến trực tiếp thay vì bọc useMemo.',
    appliesTo: ['Component'],
  },
  {
    code: 'RULE-LIST-001',
    name: 'Unified Filters State in ListPage',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'src/components/**/*ListPage.tsx',
    description: 'Gom các bộ lọc tìm kiếm và phân trang vào 1 object state filters duy nhất trong ListPage.',
    fix: 'Khởi tạo 1 state filters: const [filters, setFilters] = useState({ page: 1, ... });',
    appliesTo: ['ListPage'],
  },
  {
    code: 'RULE-LIST-003',
    name: 'Debounce Search Input Before Query Hook',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'src/components/**/*ListPage.tsx',
    description: 'Phải sử dụng useDebounce(filters.search, 300) trước khi truyền vào query hook.',
    fix: 'Bọc từ khóa tìm kiếm qua useDebounce với độ trễ 300ms.',
    appliesTo: ['ListPage'],
  },
  {
    code: 'RULE-LIST-004',
    name: 'Use Pagination Constants (DEFAULT_LIMIT)',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.LOW,
    scope: 'src/components/**/*ListPage.tsx',
    description: 'Không viết cứng magic number kích thước trang (20, 50). Phải dùng DEFAULT_LIMIT từ constants.',
    fix: 'Import DEFAULT_LIMIT hoặc LIMIT_OPTIONS từ constants.',
    appliesTo: ['ListPage'],
  },
  {
    code: 'RULE-REPO-001',
    name: 'Prettier 2 Spaces & EditorConfig Consistency',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.LOW,
    scope: '.prettierrc, .editorconfig',
    description: 'Kiểm tra cấu hình format tabWidth: 2 và EditorConfig nhất quán.',
    fix: 'Đặt tabWidth: 2 trong cấu hình Prettier.',
    appliesTo: ['Repository'],
  },
  {
    code: 'RULE-REPO-003',
    name: 'Git Branch Naming Standard (dev_<name>_<feature>)',
    category: RULE_CATEGORY.NAMING_CONVENTION,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'Git HEAD branch',
    description: 'Tên branch phải tuân thủ định dạng dev_<tên>_<tính-năng>.',
    fix: 'Đặt tên branch theo mẫu: dev_hieu_auth-flow.',
    appliesTo: ['Git'],
  },
  {
    code: 'RULE-REPO-004',
    name: 'Conventional Commits Standard (8 Types)',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.LOW,
    scope: 'Git Commits',
    description: 'Thông điệp commit phải tuân thủ Conventional Commits (feat, fix, docs, style, refactor, test, chore, perf).',
    fix: 'Viết commit theo chuẩn: feat(scope): subject.',
    appliesTo: ['Git'],
  },
  {
    code: 'RULE-GENERATED-001',
    name: 'Verify routeTree.gen.ts Generated Integrity',
    category: RULE_CATEGORY.ROUTER_ARCHITECTURE,
    severity: RULE_SEVERITY.INFO,
    scope: 'src/routeTree.gen.ts',
    description: 'Cảnh báo khi routeTree.gen.ts bị thay đổi trong worktree để đảm bảo được sinh tự động.',
    fix: 'Chạy script sinh route tự động của TanStack Router.',
    appliesTo: ['Router'],
  },
  {
    code: 'RULE-STANDARDS-001',
    name: 'Standards Document Integrity & Drift Detection',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.INFO,
    scope: '.agents/rules/**, .agents/guides/**',
    description: 'Phát hiện sự thay đổi hoặc cập nhật mới trong 6 tài liệu chuẩn hóa của dự án.',
    fix: 'Đối chiếu lại các thay đổi trong tài liệu quy chuẩn hoặc chạy satek-lint --update-standards-snapshot.',
    appliesTo: ['Repository'],
  },
  {
    code: 'RULE-COMMENT-001',
    name: 'Comment References Rule or Section Number',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.INFO,
    scope: 'Toàn bộ file nguồn',
    description: 'Cấm viết comment dẫn chiếu số mục hoặc số quy tắc cố định (vd: // mục 3.2, // quy tắc 4).',
    fix: 'Giải thích lý do nghiệp vụ thuần túy, dùng tiền tố quy ước: // QUYỀN:, // LOGIC:, // UI:.',
    appliesTo: ['Component', 'Page', 'Common'],
  },
  {
    code: 'RULE-REPO-002',
    name: 'Missing Build Script for Quality Gate',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.HIGH,
    scope: 'package.json',
    description: 'package.json phải có script "build" phục vụ kiểm tra toàn vẹn mã nguồn trong CI và pre-commit hook.',
    fix: 'Thêm script "build": "tsc -b && vite build" vào scripts trong package.json.',
    appliesTo: ['Repository'],
  },
  {
    code: 'RULE-REPO-005',
    name: 'Automated Git Hooks Quality Control with Husky',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.MEDIUM,
    scope: '.husky/pre-commit, .husky/commit-msg',
    description: 'Dự án bắt buộc cấu hình Husky pre-commit và commit-msg hook để kiểm soát format, lint, build và branch name.',
    fix: 'Khởi tạo Husky hooks (.husky/pre-commit chạy format, lint, build và .husky/commit-msg chạy commitlint).',
    appliesTo: ['Repository'],
  },
  {
    code: 'RULE-HELPER-001',
    name: 'Domain Logic Leaking Into Pure Utils',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.LOW,
    scope: 'src/utils/**',
    description: 'src/utils/ chỉ chứa pure helpers phi nghiệp vụ, không được import Entity/DTO hoặc component từ features.',
    fix: 'Di chuyển hàm xử lý nghiệp vụ sang src/helpers/ hoặc thư mục helpers/ của chính feature.',
    appliesTo: ['Utils'],
  },
  {
    code: 'RULE-QUERY-002',
    name: 'Query Params Non-Serializable / Unconstrained Type',
    category: RULE_CATEGORY.API_INTEGRATION,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'RTK Query endpoint query params',
    description: 'Cấm định nghĩa tham số query bằng Record<string, any> hoặc any tùy tiện. Bắt buộc dùng DTO interface cụ thể.',
    fix: 'Khai báo interface hoặc type tham số rõ ràng kế thừa RequestCriteria/QueryParams.',
    appliesTo: ['API'],
  },
  {
    code: 'RULE-QUERY-003',
    name: 'Missing Default Pagination Fallback',
    category: RULE_CATEGORY.API_INTEGRATION,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'RTK Query list endpoints',
    description: 'Endpoint danh sách phân trang bắt buộc phải gán giá trị mặc định page ?? 1 và limit ?? DEFAULT_LIMIT.',
    fix: 'Thêm fallback page: params?.page ?? 1, limit: params?.limit ?? DEFAULT_LIMIT.',
    appliesTo: ['API'],
  },
  {
    code: 'RULE-QUERY-004',
    name: 'Raw Status "all" Sent to Backend API',
    category: RULE_CATEGORY.API_INTEGRATION,
    severity: RULE_SEVERITY.HIGH,
    scope: 'RTK Query endpoints & filter params',
    description: 'Tuyệt đối không gửi status: "all" lên backend API vì backend sẽ tìm bản ghi có status="all" và trả về mảng rỗng.',
    fix: 'Lọc bỏ status "all": if (status && status !== "all") { queryParams.status = status; }',
    appliesTo: ['API'],
  },
  {
    code: 'RULE-QUERY-005',
    name: 'Search Query Missing .trim() Hygiene',
    category: RULE_CATEGORY.API_INTEGRATION,
    severity: RULE_SEVERITY.LOW,
    scope: 'RTK Query search params',
    description: 'Luôn gọi .trim() đối với chuỗi tìm kiếm trước khi đưa vào queryParams để tránh gửi request chỉ chứa khoảng trắng.',
    fix: 'Bọc tìm kiếm: const trimmed = search?.trim(); if (trimmed) queryParams.search = trimmed;',
    appliesTo: ['API'],
  },
  {
    code: 'RULE-QUERY-007',
    name: 'Date/Null/Relation Query Syntax Standards',
    category: RULE_CATEGORY.API_INTEGRATION,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'RTK Query searchDate, searchNull, searchHas',
    description: 'Tuân thủ cú pháp RequestCriteria: searchDate (YYYY-MM-DD hoặc start,end|field), searchNull (field hoặc field:not), searchHas (rel hoặc rel:not).',
    fix: 'Kiểm tra và sửa lại cú pháp query theo bảng tra cứu query_guides.md.',
    appliesTo: ['API'],
  },
  {
    code: 'RULE-QUERY-008',
    name: 'Delimiter Standard (include uses comma, filter uses semicolon)',
    category: RULE_CATEGORY.API_INTEGRATION,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'RTK Query params (include, filter)',
    description: 'Tham số include (eager loading) dùng dấu phẩy (,), tham số filter (sparse fieldset) dùng dấu chấm phẩy (;).',
    fix: 'Dùng include="rel1,rel2" và filter="field1;field2".',
    appliesTo: ['API'],
  },
  {
    code: 'RULE-QUERY-009',
    name: 'Multi-condition Search Missing searchJoin=and',
    category: RULE_CATEGORY.API_INTEGRATION,
    severity: RULE_SEVERITY.INFO,
    scope: 'RTK Query search param with multiple conditions',
    description: 'Backend mặc định OR cho tham số search nhiều điều kiện (field1:val1;field2:val2). Nếu muốn tìm AND, bắt buộc thêm searchJoin=and.',
    fix: 'Thêm searchJoin: "and" vào queryParams nếu mục đích tìm kiếm là thỏa mãn đồng thời các điều kiện.',
    appliesTo: ['API'],
  },
  {
    code: 'RULE-LOADING-001',
    name: 'Use isFetching Instead of isLoading for Table Re-querying',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'Table & List Components consuming RTK Query',
    description: 'isLoading chỉ bằng true ở lần đầu tiên. Khi đổi trang hoặc bộ lọc, phải dùng isFetching để hiển thị loading spinner.',
    fix: 'Truyền prop loading: isFetching || isLoading cho Table.',
    appliesTo: ['Component', 'Page'],
  },
  {
    code: 'RULE-NULL-001',
    name: 'Deep Payload Access Missing Optional Chaining / Nullish Guard',
    category: RULE_CATEGORY.TYPE_SAFETY,
    severity: RULE_SEVERITY.LOW,
    scope: 'API response access in components',
    description: 'Sử dụng toán tử optional chaining (?.) và nullish coalescing (??) khi đọc dữ liệu sâu từ API payload (data?.data?.[0]).',
    fix: 'Thêm ?. và fallback ?? [] hoặc ?? "" khi đọc thuộc tính API.',
    appliesTo: ['Component', 'Page'],
  },
  {
    code: 'RULE-LIST-002',
    name: 'Multiple Filter Updaters Missing Unified updateFilter Auto-resetting Page',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'List Pages (*ListPage.tsx)',
    description: 'Trang danh sách phải sử dụng 1 hàm updateFilter duy nhất bọc bằng useCallback, tự động reset page: 1 khi đổi tiêu chí lọc.',
    fix: 'Tạo hàm const updateFilter = useCallback((updates) => setFilters(prev => ({ ...prev, ...updates, page: updates.page ?? 1 })), []);',
    appliesTo: ['Page'],
  },
  {
    code: 'RULE-LIST-005',
    name: 'Inline Table pagination={{...}} Object Missing useMemo',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'List Pages & Tables',
    description: 'Tạo inline object pagination={{ ... }} trực tiếp trong JSX gây re-render thừa. Bắt buộc gom cấu hình vào useMemo.',
    fix: 'Bọc paginationConfig = useMemo(() => ({ ... }), [apiPagination, filters.page, filters.limit, updateFilter]);',
    appliesTo: ['Component', 'Page'],
  },
  {
    code: 'RULE-LIST-006',
    name: 'Tab Metadata Declared Inside Component or Missing Localized Memoization',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MEDIUM,
    scope: 'List Pages & Tabs components',
    description: 'Mảng metadata cấu hình tab phải đặt ngoài component module scope; nhãn đa ngôn ngữ phải memoize qua useMemo(..., [trans]).',
    fix: 'Khai báo const FILTER_TAB_CONFIG bên ngoài component function.',
    appliesTo: ['Component', 'Page'],
  },
  {
    code: 'RULE-MOCK-002',
    name: 'Production Code Importing From Mock Modules',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.RECOMMEND,
    scope: 'Production code (src/**/*.{ts,tsx})',
    description: 'Mã nguồn production đang sử dụng dữ liệu mock từ "@/mocks". Khuyến nghị thay thế bằng RTK Query hooks hoặc API service thực tế khi backend hoàn tất API.',
    fix: 'Chuyển sang RTK Query hooks hoặc query: (params) => ({ url: "...", params }) khi backend deploy API.',
    appliesTo: ['Component', 'API', 'Slice'],
  },
  {
    code: 'RULE-FORM-001',
    name: 'Form State Fragmentation / Formik + Yup Mandate',
    category: RULE_CATEGORY.FORM_VALIDATION,
    severity: RULE_SEVERITY.RECOMMEND,
    scope: 'Modal & Form components (*Modal.tsx, *Form.tsx)',
    description: 'Biểu mẫu nghiệp vụ bắt buộc sử dụng Formik (useFormik) kết hợp Yup Validation Schema, tránh phân mảnh nhiều useState rời rạc.',
    fix: 'Chuyển đổi sang useFormik({ initialValues, validationSchema, enableReinitialize: true, onSubmit }). Xem mẫu tại form_and_validation_guide.md §1.',
    appliesTo: ['Form', 'Modal'],
  },
  {
    code: 'RULE-FORM-002',
    name: 'Pure Yup Schema Mandate (No trans in Schema)',
    category: RULE_CATEGORY.FORM_VALIDATION,
    severity: RULE_SEVERITY.RECOMMEND,
    scope: 'Yup validation schemas (*.ts, *.tsx)',
    description: 'Yup schema ở Module Scope bắt buộc phải độc lập và chỉ chứa Raw English Keys. Tuyệt đối không truyền trans vào schema.',
    fix: 'Bỏ trans() trong schema: dùng Yup.string().required(\'Name is required\') và bọc {trans(formik.errors.name)} tại JSX để đổi ngôn ngữ realtime.',
    appliesTo: ['Schema', 'Component'],
  },
  {
    code: 'RULE-FORM-003',
    name: 'Anti-Race Condition in Custom Inputs (shouldValidate = false)',
    category: RULE_CATEGORY.FORM_VALIDATION,
    severity: RULE_SEVERITY.RECOMMEND,
    scope: 'Custom input change handlers (*.tsx)',
    description: 'Khi cập nhật Custom Input (React-Select), luôn truyền shouldValidate = false cho setFieldTouched để tránh Race Condition.',
    fix: 'Sửa thành: formik.setFieldTouched(field, true, false) và để setFieldValue validate giá trị mới.',
    appliesTo: ['Form', 'Component'],
  },
];
