/**
 * ============================================================================
 * UNIVERSAL FRONTEND & SATEK RULE CATALOG
 * ============================================================================
 */

export const RULE_SEVERITY = {
  CRITICAL: 'CRITICAL',
  MAJOR: 'MAJOR',
  MINOR: 'MINOR',
  INFO: 'INFO',
};

export const RULE_CATEGORY = {
  COLOR_TOKENS: 'Zero Arbitrary Colors (SSOT)',
  BORDER_RADIUS: 'Semantic Border Radius Tokens',
  THEME_SSOT: 'Design Tokens & CSS Variables',
  ROUTER_ARCHITECTURE: 'Thin Route & Router Architecture',
  NAMING_CONVENTION: 'Naming & Dynamic Param Standard',
  CIRCULAR_DEPENDENCY: 'Module & Circular Import Hygiene',
  BARREL_EXPORTS: 'Barrel Exports & Entrypoint Architecture',
  API_INTEGRATION: 'API & State Management Standards',
  RTK_QUERY: 'RTK Query Cache Tags & Mutation Standard',
  FOLDER_COLOCATION: 'Folder Co-location & Hierarchy Hygiene',
  LAYER_BOUNDARIES: 'Layer Boundary & Architectural Hierarchy',
  TYPE_SAFETY: 'TypeScript Strict Typing & Naming',
  REACT_PATTERNS: 'React Component & Hook Patterns',
  HTML_STANDARDS: 'HTML & Accessibility Standards',
  SECURITY: 'Security & Auth Storage Standards',
  CLEAN_CODE: 'Dead Code & Mock Data Hygiene',
};

export const RULES = [
  // ==========================================================================
  // NHÓM 1: ZERO ARBITRARY COLORS & DESIGN TOKENS
  // ==========================================================================
  {
    code: 'RULE-COLOR-001',
    name: 'Arbitrary Hex / Dynamic Color in ClassName',
    category: RULE_CATEGORY.COLOR_TOKENS,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'tailwind',
    scope: 'Toàn bộ UI Component, Page, Common (src/**/*.{tsx,jsx,ts})',
    description: 'Tuyệt đối không sử dụng arbitrary colors dạng [#...], [var(...)], [rgb(...)], hoặc dynamic [${...}] trong className.',
    fix: 'Thay thế bằng Tailwind semantic tokens từ @theme: text-primary, bg-bg-card, border-border-1, text-primary-navy...',
    matchRegex: /\b(text|bg|border|ring|fill|stroke|from|to|via|outline|shadow|decoration|accent|divide|placeholder)-\[(?:#[0-9a-fA-F]{3,8}|rgba?\([^)]+\)|hsla?\([^)]+\)|oklch\([^)]+\)|oklab\([^)]+\)|hwb\([^)]+\)|color\([^)]+\)|var\(--[^)]+\)|\$\{[^}]+\}|color:[^\]]+)\]/g,
    appliesTo: ['Component', 'Page', 'Common'],
  },
  {
    code: 'RULE-COLOR-002',
    name: 'Raw Hex Literal in Inline Style / SVG',
    category: RULE_CATEGORY.COLOR_TOKENS,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'tailwind',
    scope: 'Inline style & SVG elements (src/**/*.{tsx,jsx}) (Loại trừ file *Brand*, *Logo*, *VietQR* & initial form brandColor)',
    description: 'Không viết cứng mã màu hex dạng #123456 trong inline style, style object hoặc thuộc tính SVG.',
    fix: 'Dùng CSS variables hoặc Tailwind theme tokens: currentColor, var(--color-primary)...',
    matchRegex: /(?:['"`]|(?:fill|stroke)=['"]?)#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\b/g,
    appliesTo: ['Component', 'SVG'],
  },
  {
    code: 'RULE-RADIUS-001',
    name: 'Hardcoded Arbitrary Radius',
    category: RULE_CATEGORY.BORDER_RADIUS,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ UI Component, Card, FormField, Tile, Modal (src/**/*.{tsx,jsx}) (Cho phép rounded-full, rounded-pill, rounded-[inherit], rounded-none và // -- CUSTOM_RADIUS)',
    description: 'Không dùng class bo góc Tailwind mặc định hoặc arbitrary (rounded-2xl, rounded-3xl, rounded-xl, rounded-lg, rounded-md, rounded-sm, rounded-[...]). Cho phép rounded-none, rounded-[inherit], rounded-full và rounded-pill. Có thể dùng // -- CUSTOM_RADIUS khi cần bo góc vi mô đặc thù.',
    fix: 'Thay bằng 4 semantic tokens: rounded-card (Container/Card), rounded-field (Input/Button), rounded-tile (StatCard/ItemBox), rounded-pill/rounded-full (Badge/Pill/Dot/Avatar/Spinner/Switch).',
    matchRegex: /(?:^|[\s"'`])(?:[a-zA-Z0-9_-]+:)*rounded(?:-(?:t|b|l|r|tl|tr|bl|br|s|e|ss|se|ee|es))?-(?:2xl|3xl|xl|lg|md|sm|xs|\[(?!(?:inherit)\])[^\]]+\])/g,
    appliesTo: ['Card', 'Container', 'FormField', 'Tile', 'Badge'],
  },
  {
    code: 'RULE-ZINDEX-001',
    name: 'Non-Standard Arbitrary Z-Index Token',
    category: RULE_CATEGORY.THEME_SSOT,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'tailwind',
    scope: 'Toàn bộ UI Component, Modal, Header, Dropdown (src/**/*.{tsx,jsx,css})',
    description: 'Không tự chế arbitrary z-index tự do (z-[9999], z-[99999]). Bắt buộc dùng thang z-index chuẩn SSOT: z-[1000] (dropdown), z-[1050] (sticky header), z-[1060] (modal), z-[10000] (toast).',
    fix: 'Thay bằng z-index tokens chuẩn: z-[1000] (Dropdown), z-[1050] (Navbar/Header), z-[1060] (Modal/Drawer), z-[10000] (Toast/Portal).',
    matchRegex: /\bz-\[(?!(?:1000|1050|1060|10000)\])[^\]]+\]/g,
    appliesTo: ['Component', 'Modal', 'Header'],
  },
  {
    code: 'RULE-THEME-001',
    name: 'Legacy UI Design Token Constant Object',
    category: RULE_CATEGORY.THEME_SSOT,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'tailwind',
    scope: 'Toàn bộ file nguồn (src/**/*.{ts,tsx,js,jsx})',
    description: 'Cấm tạo hằng số object lưu design tokens lồng nhau (ADMIN_UI_TOKENS, UI_TOKENS, DESIGN_TOKENS). Phải sử dụng CSS @theme và Tailwind semantic tokens.',
    fix: 'Chuyển toàn bộ design tokens vào src/index.css (@theme) hoặc dùng class utility semantic.',
    matchRegex: /\b(?:export\s+)?const\s+(?:ADMIN_UI_TOKENS|UI_TOKENS|DESIGN_TOKENS|THEME_TOKENS|APP_COLORS)\b/g,
    appliesTo: ['Component', 'Store', 'Config'],
  },
  {
    code: 'RULE-UI-001',
    name: 'Forbidden display: contents on Table & Complex Grid Elements',
    category: RULE_CATEGORY.HTML_STANDARDS,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'universal',
    scope: 'Các phần tử Bảng (table, thead, tbody, tr, th, td) và Data Grid (src/**/*.{tsx,jsx,css})',
    description: 'Cấm sử dụng display: contents (hoặc class contents) trực tiếp trên các thẻ Bảng (table, thead, tbody, tr, th, td) hoặc cấu trúc Data Grid phức tạp do phá vỡ cấu trúc bảng HTML chuẩn và accessibility tree.',
    fix: 'Sử dụng React Fragment (<>...</>) hoặc các thẻ bảng chuẩn (tr, td, th) thay vì ép display: contents lên phần tử bảng.',
    matchRegex: null,
    appliesTo: ['Table', 'Grid', 'Component'],
  },

  // ==========================================================================
  // NHÓM 2: ROUTER & ROUTE ARCHITECTURE
  // ==========================================================================
  {
    code: 'RULE-ROUTE-001',
    name: 'Thick Route Component (JSX in Route File)',
    category: RULE_CATEGORY.ROUTER_ARCHITECTURE,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'router',
    scope: 'Thư mục src/routes/**/*.{tsx,jsx} (Route files, trừ __root và _layout/pathless)',
    description: 'File trong thư mục routes/ không được chứa JSX giao diện phức tạp, chỉ được khai báo route, search params và delegate cho Page component.',
    fix: 'Chuyển toàn bộ JSX sang src/components/{module}/pages/{Module}Page.tsx và render 1 dòng tại route file.',
    matchRegex: null,
    appliesTo: ['Route'],
  },
  {
    code: 'RULE-ROUTE-002',
    name: 'Route File Direct Hooks / State / Mutation Call',
    category: RULE_CATEGORY.ROUTER_ARCHITECTURE,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'router',
    scope: 'Thư mục src/routes/**/*.{tsx,jsx} (Route files, trừ __root và _layout/pathless)',
    description: 'File trong thư mục routes/ không được trực tiếp gọi useState, useEffect, useQuery, useMutation.',
    fix: 'Chuyển logic state và API call/query vào Page Orchestrator Component trong src/components/{module}/pages/.',
    matchRegex: null,
    appliesTo: ['Route'],
  },
  {
    code: 'RULE-ROUTE-003',
    name: 'Missing createFileRoute / createLazyFileRoute',
    category: RULE_CATEGORY.ROUTER_ARCHITECTURE,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'router',
    scope: 'Thư mục src/routes/**/*.{tsx,jsx} (Route files, trừ __root và _layout/pathless)',
    description: 'Mọi file trong routes/ (trừ layout/root) bắt buộc phải sử dụng createFileRoute hoặc createLazyFileRoute của TanStack Router.',
    fix: 'Khởi tạo route bằng createFileRoute(\'...\') hoặc createLazyFileRoute(\'...\').',
    matchRegex: null,
    appliesTo: ['Route'],
  },
  {
    code: 'RULE-ROUTE-006',
    name: 'Dead Route File (Missing Route Export)',
    category: RULE_CATEGORY.ROUTER_ARCHITECTURE,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'router',
    scope: 'Thư mục src/routes/**/*.{tsx,jsx} (Tất cả file route)',
    description: 'File route trong routes/ phải export hằng số Route (export const Route = ...).',
    fix: 'Thêm export const Route = createFileRoute(...) hoặc createLazyFileRoute(...).',
    matchRegex: null,
    appliesTo: ['Route'],
  },
  {
    code: 'RULE-PARAM-001',
    name: 'Fragmented Dynamic Param Name',
    category: RULE_CATEGORY.NAMING_CONVENTION,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Tên file dynamic routes trong src/routes/**/$*.tsx',
    description: 'Tên file dynamic route không được dùng tên phân mảnh như $domainId, $ticketId, $aiId, $emailId. Phải dùng $id.tsx hoặc $id.lazy.tsx.',
    fix: 'Đổi tên file thành $id.tsx hoặc $id.lazy.tsx theo chuẩn thống nhất.',
    matchRegex: /\$(?!id\b)[a-zA-Z0-9_]+\.(tsx|ts)/g,
    appliesTo: ['RoutePath'],
  },

  // ==========================================================================
  // NHÓM 3: MODULE & BARREL EXPORTS
  // ==========================================================================
  {
    code: 'RULE-BARREL-001',
    name: 'Missing Feature Barrel Entrypoint',
    category: RULE_CATEGORY.BARREL_EXPORTS,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'architecture',
    scope: 'Thư mục module feature tại src/components/<feature>/index.ts',
    description: 'Mỗi module feature tại src/components/<feature>/ bắt buộc phải có index.ts làm entrypoint duy nhất và export các thư mục con tồn tại (pages, shared, tabs, steps).',
    fix: 'Tạo file src/components/{feature}/index.ts và export * from các thư mục con.',
    matchRegex: null,
    appliesTo: ['FeatureModule'],
  },
  {
    code: 'RULE-BARREL-002',
    name: 'Route Deep Import Violation',
    category: RULE_CATEGORY.BARREL_EXPORTS,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'architecture',
    scope: 'Thư mục src/routes/**/*.{tsx,jsx} khi import component',
    description: 'File trong routes/ bắt buộc phải import Page component thông qua barrel export @/components/<feature>, cấm import sâu từ @/components/<feature>/pages/...',
    fix: 'Sử dụng import { ... } from \'@/components/{feature}\' thay vì import sâu vào pages/.',
    matchRegex: /from\s+['"]@\/components\/[a-zA-Z0-9_-]+\/(?:pages|shared|tabs|steps)\b/g,
    appliesTo: ['Route'],
  },
  {
    code: 'RULE-IMPORT-001',
    name: 'Self Circular Barrel Import',
    category: RULE_CATEGORY.CIRCULAR_DEPENDENCY,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'ci',
    scope: 'Toàn bộ file nguồn src/**/*.{ts,tsx,js,jsx} (Cấm import từ ./index, ./ hoặc . trong cùng thư mục)',
    description: 'Các file trong cùng thư mục không được import từ chính ./index, ./ hoặc . gây vòng lặp import.',
    fix: 'Sử dụng relative import trực tiếp từ file anh em: ./SiblingComponent thay vì ./index hoặc .',
    matchRegex: /from\s+['"](?:\.\/index|\.\/|\.)['"]/g,
    appliesTo: ['Component', 'Utils', 'Helpers'],
  },
  {
    code: 'RULE-IMPORT-003',
    name: 'Upward Layer Architectural Import Violation',
    category: RULE_CATEGORY.LAYER_BOUNDARIES,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'architecture',
    scope: 'Tầng kiến trúc dưới: src/store/**, src/types/**, src/utils/**, src/components/common/**',
    description: 'Cấm import ngược tầng kiến trúc: store/types/utils không được import từ components/routes; components/common không được import từ components/<feature>.',
    fix: 'Chuyển dependency theo chiều xuôi: components phụ thuộc store/types/utils, không được import ngược.',
    matchRegex: null,
    appliesTo: ['Store', 'Types', 'Utils', 'Common'],
  },
  {
    code: 'RULE-API-002',
    name: 'Deep API Slice Import Violation',
    category: RULE_CATEGORY.CIRCULAR_DEPENDENCY,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ Component & Pages (src/components/**/*.{tsx,jsx}, src/routes/**/*.{tsx,jsx})',
    description: 'Component không được import sâu từ @/store/api/*Api. Phải import qua barrel tập trung @/store/api.',
    fix: 'Import toàn bộ API hooks thông qua barrel export tập trung: import { ... } from \'@/store/api\'.',
    matchRegex: /from\s+['"]@\/store\/api\/[a-zA-Z0-9]+Api['"]/g,
    appliesTo: ['Component', 'Pages'],
  },

  // ==========================================================================
  // NHÓM 4: API & RTK QUERY STANDARDS
  // ==========================================================================
  {
    code: 'RULE-API-001',
    name: 'Direct Raw Fetch / Axios Outside BaseApi',
    category: RULE_CATEGORY.API_INTEGRATION,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'universal',
    scope: 'Toàn bộ file nguồn ngoài src/store/api/baseApi.ts',
    description: 'Không được gọi raw fetch(), axios, hoặc createApi() trực tiếp ngoài baseApi.ts.',
    fix: 'Sử dụng baseApi.injectEndpoints() để tự động kế thừa cơ chế 401 refresh mutex.',
    matchRegex: /(?:\b(?:window\.|globalThis\.)?fetch\s*\(|\baxios(?:\.[a-zA-Z0-9_$]+)?\s*\(|\bcreateApi\s*\()/g,
    appliesTo: ['Store', 'Component'],
  },
  {
    code: 'RULE-RTK-001',
    name: 'Missing invalidatesTags in RTK Query Resource Mutation',
    category: RULE_CATEGORY.RTK_QUERY,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'architecture',
    scope: 'Các Mutation quản lý CRUD Resource (Ngoại trừ: authApi, uploadApi/fileApi, lookup/check tools, và mutation có onQueryStarted)',
    description: 'Các mutation thay đổi dữ liệu tài nguyên (Create, Update, Delete) trong src/store/api/*.ts bắt buộc phải cấu hình invalidatesTags để tự động làm mới cache. Không áp dụng cho các API stateless như Auth, Upload, Check/Lookup hoặc mutation đã tự cập nhật qua onQueryStarted.',
    fix: 'Thêm invalidatesTags: [\'TagName\'] vào cấu hình builder.mutation({ ... }) (hoặc chú thích // -- LOGIC: nếu là mutation đặc thù).',
    matchRegex: null,
    appliesTo: ['ApiSlice'],
  },
  {
    code: 'RULE-RTK-002',
    name: 'Missing providesTags in RTK Query Resource Query',
    category: RULE_CATEGORY.RTK_QUERY,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'architecture',
    scope: 'Các Query lấy dữ liệu Resource danh sách & chi tiết (Ngoại trừ: authApi, check/lookup on-the-fly, healthcheck)',
    description: 'Các query lấy dữ liệu tài nguyên trong src/store/api/*.ts bắt buộc phải cấu hình providesTags để liên kết cache với các mutation tương ứng.',
    fix: 'Thêm providesTags: [\'TagName\'] vào cấu hình builder.query({ ... }).',
    matchRegex: null,
    appliesTo: ['ApiSlice'],
  },

  // ==========================================================================
  // NHÓM 5: FOLDER CO-LOCATION & HIERARCHY HYGIENE
  // ==========================================================================
  {
    code: 'RULE-FOLDER-001',
    name: 'Component Should Be Co-located With Context',
    category: RULE_CATEGORY.FOLDER_COLOCATION,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'architecture',
    scope: 'Thư mục src/components/<feature>/ (Component chỉ phục vụ 1 Tab/Step cụ thể)',
    description: 'Component, Modal, Dialog hoặc Form chỉ phục vụ duy nhất 1 Tab hoặc 1 Step phải được co-locate nằm trong thư mục Tab/Step đó, không được đặt ở root feature.',
    fix: 'Di chuyển component vào thư mục tabs/{tabName}/ hoặc steps/{stepName}/ tương ứng.',
    matchRegex: null,
    appliesTo: ['Component'],
  },
  {
    code: 'RULE-FOLDER-002',
    name: 'Misplaced Single-use Component in shared/',
    category: RULE_CATEGORY.FOLDER_COLOCATION,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'architecture',
    scope: 'Thư mục src/components/<feature>/shared/*.tsx',
    description: 'Thư mục components/<feature>/shared/ chỉ chứa component được gọi từ 2 trang/tab/step trở lên hoặc các component layout đặc thù (*Header, *Tabs, *Table, *Layout, *Wrapper, *Summary).',
    fix: 'Chuyển component dùng 1 lần về đúng thư mục Tab/Step sử dụng nó, hoặc đổi tên theo chuẩn shared component.',
    matchRegex: null,
    appliesTo: ['SharedComponent'],
  },
  {
    code: 'RULE-FOLDER-003',
    name: 'Legacy or Dead Feature Folder Detected',
    category: RULE_CATEGORY.FOLDER_COLOCATION,
    severity: RULE_SEVERITY.MAJOR,
    preset: 'architecture',
    scope: 'Thư mục cấu trúc phẳng cũ tại src/components/<feature>/{components,forms}/',
    description: 'Cấm tồn tại các thư mục phẳng legacy cũ (components/<feature>/components, modals, forms) sau khi feature đã cấu trúc lại theo pages/, shared/, tabs/, steps/.',
    fix: 'Di chuyển toàn bộ component sang tabs/, steps/ hoặc pages/ và xóa bỏ thư mục phẳng cũ.',
    matchRegex: null,
    appliesTo: ['DirectoryStructure'],
  },

  // ==========================================================================
  // NHÓM 6: TYPESCRIPT STRICT TYPING & NAMING
  // ==========================================================================
  {
    code: 'RULE-TYPE-001',
    name: 'Explicit Any / Unsafe Type Casting',
    category: RULE_CATEGORY.TYPE_SAFETY,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ file TypeScript (src/**/*.{ts,tsx})',
    description: 'Cấm sử dụng kiểu any, Record<string, any> hoặc (x as any).',
    fix: 'Sử dụng unknown kèm type narrowing, hoặc mở rộng interface tại src/types/.',
    matchRegex: /:\s*any\b|\bas\s+any\b|Record<string,\s*any>/g,
    appliesTo: ['TypeScript'],
  },
  {
    code: 'RULE-TYPE-002',
    name: 'Types Must Be Imported From @/types Barrel',
    category: RULE_CATEGORY.TYPE_SAFETY,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ file ngoài src/types/ (Bắt buộc import từ @/types barrel)',
    description: 'Type và Interface bắt buộc phải được import thông qua barrel @/types, cấm deep import từ @/types/*.types.',
    fix: 'Thay đổi import thành: import { ... } from \'@/types\'.',
    matchRegex: /from\s+['"]@\/types\/[a-zA-Z0-9_-]+(?:\.types)?['"]/g,
    appliesTo: ['TypeScript'],
  },
  {
    code: 'RULE-TYPE-003',
    name: 'Invalid Type File Naming in src/types/',
    category: RULE_CATEGORY.TYPE_SAFETY,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Thư mục src/types/*.ts (Trừ index.ts và index.d.ts)',
    description: 'File trong src/types/ (trừ index.ts) bắt buộc phải có đuôi .types.ts và bắt đầu bằng chữ thường (vd: auth.types.ts, domain.types.ts).',
    fix: 'Đổi tên file thành {module}.types.ts (ví dụ: auth.types.ts, domain.types.ts).',
    matchRegex: null,
    appliesTo: ['TypesDirectory'],
  },

  // ==========================================================================
  // NHÓM 7: REACT, HTML & RADIX STANDARDS
  // ==========================================================================
  {
    code: 'RULE-RADIX-001',
    name: 'Radix Trigger Wrapping Interactive Element Must Use asChild',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'universal',
    scope: 'Toàn bộ Radix UI Triggers (DialogTrigger, PopoverTrigger, TooltipTrigger, DropdownMenuTrigger...)',
    description: 'Radix Trigger (DialogTrigger, PopoverTrigger, TooltipTrigger, DropdownMenuTrigger) khi bọc button hoặc thẻ tương tác bắt buộc phải có thuộc tính asChild.',
    fix: 'Thêm thuộc tính asChild vào thẻ Trigger: <PopoverTrigger asChild><button>...</button></PopoverTrigger>.',
    matchRegex: null,
    appliesTo: ['Component'],
  },
  {
    code: 'RULE-HTML-001',
    name: 'Nested Interactive Element in JSX',
    category: RULE_CATEGORY.HTML_STANDARDS,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'universal',
    scope: 'Toàn bộ JSX elements (src/**/*.{tsx,jsx}) (Lồng button/a)',
    description: 'Cấm lồng các phần tử tương tác vào nhau trong JSX (<button><button>, <a><button>, <button><a>).',
    fix: 'Tách biệt các phần tử tương tác hoặc sử dụng thẻ <span>/<div> kèm event handler phù hợp.',
    matchRegex: null,
    appliesTo: ['JSX'],
  },
  {
    code: 'RULE-COMPONENT-001',
    name: 'Nested Component Definition in Parent Function',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ React Component functions (src/**/*.{tsx,jsx})',
    description: 'Cấm định nghĩa component con bên trong hàm render của component cha (Static Component Extraction).',
    fix: 'Đưa định nghĩa component con ra ngoài phạm vi hàm của component cha để tránh render recreate.',
    matchRegex: null,
    appliesTo: ['Component'],
  },
  {
    code: 'RULE-STATE-001',
    name: 'Non-Standard Boolean UI State Naming',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ React useState hooks trong src/**/*.{tsx,jsx}',
    description: 'State boolean UI đóng/mở/hiển thị phải có tiền tố is[Feature][State] (ví dụ: isModalOpen, isFilterVisible).',
    fix: 'Đổi tên state thành is[Feature][State], ví dụ: isPasswordVisible thay vì showPassword, isModalOpen thay vì openModal.',
    matchRegex: /const\s+\[(show[A-Z][A-Za-z0-9_]*|open[A-Z][A-Za-z0-9_]*|visible[A-Z][A-Za-z0-9_]*),\s*set[A-Z][A-Za-z0-9_]*\]\s*=\s*useState/g,
    appliesTo: ['Component'],
  },
  {
    code: 'RULE-REACT-001',
    name: 'Avoid Namespace React.FC / React.ReactNode',
    category: RULE_CATEGORY.REACT_PATTERNS,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ file TypeScript React (src/**/*.{ts,tsx})',
    description: 'Không dùng namespace React.FC, React.ReactNode, React.MouseEvent. Import từng phần: import type { FC, ReactNode } from "react".',
    fix: 'Import trực tiếp type từ react: import type { FC, ReactNode } from \'react\'.',
    matchRegex: /\bReact\.(?:FC|ReactNode|ComponentProps|MouseEvent|ChangeEvent|FormEvent|KeyboardEvent|CSSProperties|PropsWithChildren)\b/g,
    appliesTo: ['TypeScript'],
  },

  // ==========================================================================
  // NHÓM 8: CLEAN CODE, SECURITY & MOCKS
  // ==========================================================================
  {
    code: 'RULE-STORAGE-001',
    name: 'Raw String Keys in Auth Storage',
    category: RULE_CATEGORY.SECURITY,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'ci',
    scope: 'Toàn bộ file trong src/ có gọi localStorage (Auth & Token)',
    description: 'Cấm truyền string literal tùy tiện vào localStorage cho token và auth (localStorage.getItem("access_token")). Bắt buộc dùng hằng số AUTH_STORAGE_KEYS.',
    fix: 'Sử dụng hằng số chuẩn: localStorage.getItem(AUTH_STORAGE_KEYS.ACCESS_TOKEN).',
    matchRegex: /localStorage\.(?:getItem|setItem|removeItem)\(['"](?:access_token|refresh_token|token|authToken|user_token)['"]/g,
    appliesTo: ['Store', 'Component', 'Auth'],
  },
  {
    code: 'RULE-MOCK-001',
    name: 'Fake Fallback Metrics Count',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ JSX Component & Metric displays (src/**/*.{tsx,jsx})',
    description: 'Không viết fallback count số liệu giả như || 7, ?? 7, || 10, ?? 99 trong code hiển thị.',
    fix: 'Sử dụng giá trị mặc định thực tế 0 hoặc tính toán độ dài mảng chuẩn.',
    matchRegex: /\|\|\s*\d{2,}\b|\?\?\s*\d{2,}\b|\|\|\s*7\b|\?\?\s*7\b/g,
    appliesTo: ['Component', 'Mocks'],
  },
  {
    code: 'RULE-MOCK-002',
    name: 'Production Code Importing From Mock Modules',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'ci',
    scope: 'Mã nguồn production (src/components/**, src/routes/**, src/store/**)',
    description: 'Cấm import mock data (@/mocks/*, ../mocks/*) trong các file nguồn production (components/, pages/, routes/).',
    fix: 'Thay thế dữ liệu mock bằng RTK Query hooks hoặc API service thực tế.',
    matchRegex: null,
    appliesTo: ['Component', 'Routes'],
  },
  {
    code: 'RULE-DEAD-001',
    name: 'Constant Binary Expression in JSX',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ JSX blocks (src/**/*.{tsx,jsx})',
    description: 'Tuyệt đối không sử dụng biểu thức {false && <Component />} trong JSX gây lỗi no-constant-binary-expression.',
    fix: 'Sử dụng khối comment JSX {/* <Component /> */} hoặc biến cờ điều kiện động.',
    matchRegex: /\{\s*false\s*&&/g,
    appliesTo: ['JSX'],
  },
  {
    code: 'RULE-CONSOLE-001',
    name: 'Production console.log Statement',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Mã nguồn production (src/**/*.{ts,tsx,js,jsx}) ngoài src/utils/logger và test files',
    description: 'Cấm sử dụng console.log, console.debug, console.info trong mã nguồn production. Sử dụng logger utility nếu cần ghi log.',
    fix: 'Xóa bỏ console statement hoặc dùng logger module chuyên dụng.',
    matchRegex: /\bconsole\.(?:log|debug|info)\s*\(/g,
    appliesTo: ['Component', 'Store', 'Routes'],
  },
  {
    code: 'RULE-SUPPRESS-001',
    name: 'Suppression Comments Without Justification',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ file nguồn có comment vô hiệu hóa linter (@ts-ignore, @ts-expect-error, eslint-disable)',
    description: 'Comment vô hiệu hóa linter (@ts-ignore, @ts-expect-error, eslint-disable) bắt buộc phải có phần giải thích lý do sau dấu -- LOGIC: ...',
    fix: 'Thêm lý do giải thích rõ ràng sau comment: // eslint-disable-next-line -- LOGIC: lý do tại đây.',
    matchRegex: /(?:\/\/|\/\*)\s*(?:@ts-ignore|@ts-nocheck|@ts-expect-error|eslint-disable(?:-next-line)?(?:\s+[\w\-,\s\/]+)?)\s*(?!--\s*LOGIC:)(?:\*\/)?$/g,
    appliesTo: ['Component', 'Store', 'TypeScript'],
  },
  {
    code: 'RULE-I18N-001',
    name: 'Hardcoded Vietnamese UI Text in JSX',
    category: RULE_CATEGORY.CLEAN_CODE,
    severity: RULE_SEVERITY.MINOR,
    preset: 'migration',
    scope: 'Toàn bộ JSX UI Text, Props & String literals (src/**/*.{tsx,jsx,ts}) (Trừ locales/ và mocks/)',
    description: 'Không viết cứng chuỗi tiếng Việt có dấu trực tiếp trong JSX. Phải sử dụng hàm dịch trans(\'...\') hoặc file locales.',
    fix: 'Bọc chuỗi hiển thị bằng trans(\'...\') hoặc khai báo trong src/locales/.',
    matchRegex: null,
    appliesTo: ['JSX'],
  },
  {
    code: 'RULE-ROUTE-005',
    name: 'Prefer <Link> for Static Navigation',
    category: RULE_CATEGORY.ROUTER_ARCHITECTURE,
    severity: RULE_SEVERITY.INFO,
    preset: 'migration',
    scope: 'Toàn bộ static onClick navigation (src/**/*.{tsx,jsx})',
    description: 'Khuyến nghị sử dụng component <Link to="..."> thay vì gọi router.navigate() hoặc navigate({ to: \'...\' }) trong onClick tĩnh.',
    fix: 'Thay thế button onClick={navigate} bằng <Link to="...">...</Link>.',
    matchRegex: null,
    appliesTo: ['Component', 'Pages'],
  },
  {
    code: 'RULE-HTML-002',
    name: 'Invalid Nested Table Cell',
    category: RULE_CATEGORY.HTML_STANDARDS,
    severity: RULE_SEVERITY.CRITICAL,
    preset: 'ci',
    scope: 'Toàn bộ JSX Table elements (src/**/*.{tsx,jsx}) (Lồng th trong th, td trong td)',
    description: 'Cấm lồng các ô bảng vào nhau trong JSX (<th><th> hoặc <td><td>).',
    fix: 'Đặt các thẻ <th> và <td> cùng cấp bên trong thẻ <tr>.',
    matchRegex: null,
    appliesTo: ['JSX'],
  },
  {
    code: 'RULE-CUSTOM-001',
    name: 'Excessive Arbitrary Tailwind Classes',
    category: RULE_CATEGORY.THEME_SSOT,
    severity: RULE_SEVERITY.INFO,
    preset: 'migration',
    scope: 'Toàn bộ JSX className (src/**/*.{tsx,jsx}) (> 3 arbitrary classes [..])',
    description: 'Phần tử có quá nhiều arbitrary utilities dạng [...] (> 3 arbitrary classes). Nên trích xuất thành class utility hoặc component chuẩn.',
    fix: 'Sử dụng các class Tailwind chuẩn hoặc trích xuất biến thể component dùng chung.',
    matchRegex: null,
    appliesTo: ['Component'],
  },
];
